### ISSUE TITLE
关于缺失依赖模块的问题

### ISSUE THREAD

**Issue by RBqingkong** [kivenZhou/next#1]
想问一下package文件是否有误，我npm i之后启动项目，有报错说依赖模块缺失。

![1](https://user-images.githubusercontent.com/29622854/33315775-a24eb1c4-d46c-11e7-9744-e8c847a57bc6.png)

**Comment by kivenZhou** [comment]
@RBqingkong 建议你先把node_modules删除掉，重新npm install一下，有可能是install的时候一些依赖没有下载完整！
