### ISSUE TITLE
ListView.DataSource的作用

### ISSUE THREAD

**Issue by Alisa0026** [kivenZhou/next#2]
hello~我看到你关于antd-mobile中listview的提问~我想有个小问题咨询一下，就是关于ListView.DataSource这个传的4各参数的作用，感觉自己没有很理解，能请教一下嘛

**Comment by kivenZhou** [comment]
DataSource是ListView的数据源设置，项目中引用时使用了rowHasChanged，里面2个参数，分别代表当前数据源与接收到的新的数据源，要更新datasource中的数据，调用cloneWithRows方法将数据导入，clone方法会自动提取新数据并进行对比，这样ListView就知道哪些行需要重新渲染了
